/* AI4FH Lab — Content data */

window.LAB = {
  name: "AI4FH Lab",
  fullName: "Artificial Intelligence for Food & Health",
  tagline: "We build AI systems that read the language of biology — peptides, proteins, microbes — and turn it into food and health.",
  affiliation: "School of Biosystems & Food Engineering",
  university: "University College Dublin",
  location: "Dublin, Ireland",
  email: "zhenjiao.du@ucd.ie",
  founded: "June 2025",
};

window.PI = {
  name: "Zhenjiao Du, PhD",
  title: "Ad Astra Fellow · Assistant Professor",
  affiliation: "School of Biosystems & Food Engineering, UCD",
  email: "zhenjiao.du@ucd.ie",
  photo: "images/002_square.jpg",
  bio: [
    "Postdoc, Duke University (USA), 2025",
    "Ph.D. Kansas State University (USA), 2024",
    "M.E. China Agricultural University (China), 2020",
    "B.E. Wuhan Polytechnic University (China), 2018",
  ],
  links: [
    { label: "Google Scholar", url: "https://scholar.google.com/citations?user=JSRi5xEAAAAJ&hl=zh-CN&oi=ao" },
    { label: "ORCID", url: "https://orcid.org/0000-0002-8492-4328" },
    { label: "GitHub", url: "https://github.com/dzjxzyd" },
    { label: "UCD Profile", url: "https://people.ucd.ie/zhenjiao.du" },
  ],
};

window.PILLARS = [
  {
    n: "01",
    title: "Bioactive Discovery",
    body: "Leveraging AI to discover and produce bioactive peptides and small molecules from agricultural byproducts.",
    tags: ["Peptides", "pLM"],
  },
  {
    n: "02",
    title: "Smart Biomanufacturing",
    body: "Leveraging AI for rational experimental design in fermentation and biomanufacturing.",
    tags: ["Bayesian opt.", "Bioprocess"],
  },
  {
    n: "03",
    title: "Large language models for AI4Science",
    body: "Building lightweight pre-trained models for proteins, peptides, and microbial communities — small enough to fine-tune and serve.",
    tags: ["LLMs", "ESM"],
  },
  {
    n: "04",
    title: "AI for Science",
    body: "Applying LLMs and deep learning across food chemistry, nutritional science, and biochemistry.",
    tags: ["AI4Science", "LLMs"],
  },
  {
    n: "05",
    title: "Agri-Valorization",
    body: "Converting agricultural waste into high-value functional ingredients through AI-optimized processes.",
    tags: ["Impact", "Circular food"],
  },
];

window.PEOPLE = [
  {
    name: "Dr. Zhenjiao Du",
    role: "Principal Investigator",
    note: "Ad Astra Fellow · Assistant Professor",
    photo: "images/002_square.jpg",
    extra: "PhD, Kansas State · Postdoc, Duke",
    initials: "ZD",
    pi: true,
  },
  {
    name: "Qidong Xue",
    role: "PhD Student",
    note: "2025.09 - present · M.S. Jiangnan University",
    photo: "images/xqd.jpg",
    extra: "B.S. Jiangnan University",
    initials: "QX",
  },
  {
    name: "Dongyang Xu",
    role: "PhD Student",
    note: "2025.09 - present · M.S. South China University of Technology",
    photo: "images/dongyang-xu.jpg",
    extra: "B.E. Nanchang University",
    initials: "DX",
  },
  {
    name: "Chuanyu Zhang",
    role: "MSc Student",
    note: "2025 — 2026",
    photo: "images/zcy.jpg",
    extra: "B.E. Dalian University of Technology",
    initials: "CZ",
    alumni: true,
  },
  {
    name: "Muxi Yu",
    role: "MSc Student",
    note: "2025 — 2026",
    photo: null,
    extra: "B.E. Jiangsu Univ. of Science & Technology",
    initials: "MY",
    alumni: true,
  },
  {
    name: "Xiao Wang",
    role: "Volunteer - MSc Student",
    note: "2025 — 2026",
    photo: null,
    extra: "B.S. China Pharmaceutical University",
    initials: "XW",
    alumni: true,
  },
  {
    name: "Zhan Zhang",
    role: "Volunteer - MSc Student",
    note: "2025 — 2026",
    photo: "images/zz.jpg",
    extra: "B.E. Harbin University of Commerce",
    initials: "ZZ",
    alumni: true,
  },
];

window.PROJECTS = [
  {
    name: "PepBERT",
    body: "Lightweight pretrained language model for peptide representation. Small enough to fine-tune on a single GPU; strong on bioactivity benchmarks.",
    href: "https://doi.org/10.1016/j.fufo.2026.100999",
    kind: "Model",
  },
  {
    name: "FusionESP",
    body: "Enzyme–substrate pair prediction by fusing ESM-2 protein embeddings with MoLFormer substrate embeddings through specifically designed projection heads and a contrastive learning architecture.",
    href: "https://doi.org/10.1021/acs.jcim.4c02357",
    kind: "Model",
    webserver: true,
  },
  {
    name: "UniDL4BioPep",
    body: "A universal deep-learning architecture for binary classification across many bioactive peptide tasks, with a public webserver and PyTorch / Keras builds.",
    href: "https://doi.org/10.1093/bib/bbad135",
    kind: "Model",
    webserver: true,
  },
  {
    name: "pLM4ACE",
    body: "Protein language-model-based predictor for screening peptides with high antihypertensive (ACE-inhibitory) activity.",
    href: "https://doi.org/10.1016/j.foodchem.2023.137162",
    kind: "Model",
    webserver: true,
  },
  {
    name: "pLM4Alg",
    body: "Protein language-model-based predictors for allergenic proteins and peptides — a screening tool for food allergy risk.",
    href: "https://doi.org/10.1021/acs.jafc.3c07143",
    kind: "Model",
    webserver: true,
  },
  {
    name: "Antioxidant dipeptide prediction",
    body: "Computer-aided framework for predicting, screening, and designing antioxidative dipeptides — applied to sorghum proteins.",
    href: "https://doi.org/10.1021/acsfoodscitech.2c00286",
    kind: "Model",
  },
  {
    name: "Antioxidant tripeptide prediction",
    body: "Comprehensive evaluation and comparison of machine learning methods for QSAR modeling of antioxidant tripeptides.",
    href: "https://doi.org/10.1021/acsomega.2c03062",
    kind: "Model",
  },
];

window.PUBLICATIONS = [
  {
    year: "2026",
    title: "PepBERT: Lightweight language models for bioactive peptide representation",
    authors: "Du Z., Caragea D., Guo X., Li Y.",
    venue: "Future Foods",
    tags: ["Peptides", "LLM"],
    href: "https://github.com/dzjxzyd/PepBERT",
  },
  {
    year: "2025",
    title: "FusionESP: improved enzyme–substrate pair prediction by fusing protein and chemical knowledge",
    authors: "Du Z., Fu W., Guo X., Caragea D., Li Y.",
    venue: "Journal of Chemical Information and Modeling",
    tags: ["ESM", "Enzymes"],
    href: "https://github.com/dzjxzyd/FusionESP",
  },
  {
    year: "2025",
    title: "Membrane selectivity mechanisms of antimicrobial peptide Snakin-Z against prokaryotic and eukaryotic membrane models",
    authors: "Kumar N., Du Z., Amachawadi R., Guo X., Zhao J., Li Y.",
    venue: "The Journal of Physical Chemistry",
    tags: ["Peptides", "AMP"],
    href: "#",
  },
  {
    year: "2024",
    title: "pLM4ACE: a protein language model-based deep learning predictor for screening peptides with high antihypertensive activity",
    authors: "Du Z., Ding X., Hsu W., Munir A., Xu Y., Li Y.",
    venue: "Food Chemistry, 137162",
    tags: ["Peptides", "Health"],
    href: "https://github.com/dzjxzyd/pLM4ACE",
  },
  {
    year: "2024",
    title: "pLM4Alg: protein language model-based predictors for allergenic proteins and peptides",
    authors: "Du Z., Xu Y., Liu C., Li Y.",
    venue: "Journal of Agricultural and Food Chemistry, 752–760",
    tags: ["Peptides", "Allergy"],
    href: "https://github.com/dzjxzyd/pLM4Alg",
  },
  {
    year: "2023",
    title: "UniDL4BioPep: a universal deep learning architecture for binary classification in peptide bioactivity",
    authors: "Du Z., Ding X., Xu Y., Li Y.",
    venue: "Briefings in Bioinformatics, 1–10  ·  Top 1% in ESI",
    tags: ["Peptides", "DL"],
    href: "https://github.com/dzjxzyd/UniDL4BioPep",
  },
  {
    year: "2023",
    title: "Bioinformatics approaches to discovering food-derived bioactive peptides: reviews and perspectives",
    authors: "Du Z., Comer J., Li Y.",
    venue: "Trends in Analytical Chemistry, 117051  ·  Top 1% in ESI",
    tags: ["Peptides", "Review"],
    href: "#",
  },
  {
    year: "2022",
    title: "Computer-aided approaches for predicting, screening, and designing antioxidative dipeptides and application to sorghum proteins",
    authors: "Du Z., Li Y.",
    venue: "ACS Food Science & Technology, 2(11), 1781–1788",
    tags: ["Peptides"],
    href: "#",
  },
  {
    year: "2022",
    title: "Review and perspective on bioactive peptides: a roadmap for research, development, and future opportunities",
    authors: "Du Z., Li Y.",
    venue: "Journal of Agriculture and Food Research, 100353",
    tags: ["Peptides", "Review"],
    href: "#",
  },
  {
    year: "2022",
    title: "Comprehensive evaluation and comparison of machine learning methods in QSAR modeling of antioxidant tripeptides",
    authors: "Du Z., Wang D., Li Y.",
    venue: "ACS Omega, 25760–25771",
    tags: ["Peptides", "ML"],
    href: "#",
  },
  {
    year: "2022",
    title: "Quantitative assessment of wheat quality using near-infrared spectroscopy: a comprehensive review",
    authors: "Du Z., Tian W., Tilley M., Wang D., Zhang G., Li Y.",
    venue: "Comprehensive Reviews in Food Science and Food Safety, 1–54",
    tags: ["Food", "NIR"],
    href: "#",
  },
  {
    year: "2020",
    title: "Recent advances in imaging techniques for bruise detection in fruits and vegetables",
    authors: "Du Z., Zeng X., Li X., Ding X., Cao J., Jiang W.",
    venue: "Trends in Food Science & Technology, 99, 133–141",
    tags: ["Food", "Imaging"],
    href: "#",
  },
  {
    year: "2022",
    title: "Linear scaling reveals low-dimensional structure in observable microbial dynamics",
    authors: "Zhou Z., Chen X., Şimşek E., Hamrick G. S., Baig Y., Holmes Z. A., Du Z., Karig D. K., You L.",
    venue: "bioRxiv, 2025-06",
    tags: ["Microbial", "Dynamics"],
    href: "#",
  },
];

window.NEWS = [
  { date: "Aug 31, 2026", body: "Welcome Dongyang and Qidong to the AI4FH Lab.", image: "images/welcome-dongyang-qidong.jpg" },
  { date: "Jun 2025", body: "AI4FH Lab is established at UCD. We are open for PhD, MSc, and postdoc inquiries." },
];

window.NAV = [
  { id: "home", label: "Home" },
  { id: "research", label: "Research" },
  { id: "people", label: "People" },
  { id: "publications", label: "Publications" },
  { id: "news", label: "News" },
  { id: "join", label: "Open positions" },
  { id: "collab", label: "Collaborate" },
];

window.I18N = {
  en: {
    nav: {
      home: "Home",
      research: "Research",
      people: "People",
      publications: "Publications",
      news: "News",
      join: "Open positions",
      collab: "Collaborate",
    },
    chrome: {
      menu: "Menu",
      close: "Close",
      footerLab: "Lab",
      footerEngage: "Engage",
      footerElsewhere: "Elsewhere",
      openPositions: "Open positions",
      collaborate: "Collaborate",
      emailUs: "Email us",
      ucdProfile: "UCD profile",
      footerText: "Artificial Intelligence for Food & Health Lab.<br />School of Biosystems & Food Engineering,<br />University College Dublin, Ireland.",
    },
    home: {
      heroTitleA: "AI for",
      heroFood: "food",
      heroTitleB: "and",
      heroHealth: "health",
      heroLead: "We work on bioactive compound discovery, smart biomanufacturing, and large language models — releasing open-source code and public webservers, alongside wet-lab collaborations.",
      readResearch: "Read our research",
      joinLab: "Join the lab →",
      labIndex: "// LAB INDEX · LIVE",
      statModels: "Open-source models &amp; servers",
      statPublished: "Predictive models published",
      statEstablished: "Established",
      research: "Research",
      researchDirections: "Research directions",
      researchLead: "Five active threads at the AI–food–health interface.",
      seeAllResearch: "See all research →",
      openSource: "Open source",
      modelsTitle: "Models &amp; webservers from the lab",
      webserver: "WEBSERVER",
      news: "News",
      allUpdates: "All updates →",
      ctaEyebrow: "Open positions",
      ctaTitle: "Open positions",
      ctaLead: "Recruiting MSc / PhD students and postdocs. Backgrounds in ML, food chemistry, microbiology, computational chemistry, biochemistry, bioinformatics, or synthetic biology are all welcome.",
      seeOpenPositions: "See open positions",
    },
    research: {
      eyebrow: "Research",
      title: "Research",
      lead: "Five threads — bioactive discovery, smart biomanufacturing, foundation models, broader AI for science, and agri-valorization for downstream impact.",
      openSource: "Open source",
      modelsTitle: "Models, benchmarks, and webservers",
    },
    people: {
      eyebrow: "People",
      title: "People",
      lead: "The lab is led by Zhenjiao Du, with members from food chemistry, food engineering, microbiology, pharmacy, and machine learning backgrounds.",
      pi: "Principal Investigator",
      groupMembers: "Group members",
      partner: "Lab partner for life",
      partnerRole: "Lab Co-founder (unofficial, but undisputed) · Chief Happiness Officer & Moral Compass",
      joined: "Joined",
      sinceForever: "Since forever",
      funFact: "Fun fact",
      funFactText: "She's been in the lab longer than the lab has existed.",
      interests: "Interests",
      interestsText: "Maintaining work–life balance, bakery, and travel",
      email: "Email",
      alumni: "Alumni",
    },
    publications: {
      eyebrow: "Publications",
      title: "Publications",
      lead: "Selected recent work. Full list on Google Scholar.",
      viewScholar: "View on Google Scholar ↗",
    },
    news: {
      eyebrow: "News",
      title: "News",
      lead: "Updates from the lab.",
      featured: "Latest from the lab",
    },
    join: {
      eyebrow: "Open positions",
      title: "Open positions",
      lead: "Recruiting at all levels. Backgrounds in ML, food chemistry, microbiology, computational chemistry, biochemistry, bioinformatics, or synthetic biology are all welcome.",
      roles: [
        {
          title: "MSc & PhD Students",
          detail: "Fully-funded positions in AI4Science with a focus on bioactive peptides, fermentation, or microbial language models. Strong programming or wet-lab background welcome — we will help you bridge. Happy to support scholarship applications including the Government of Ireland Postgraduate Scholarship Programme and equivalent national / international schemes.",
        },
        {
          title: "Postdoctoral Scientists",
          detail: "Supporting fellowship applications welcome (MSCA, Wellcome, Research Ireland, etc.). Ideal candidates blend AI methods with a domain — biochemistry, microbiology, food chemistry, or synthetic biology.",
        },
      ],
      howToApply: "How to apply",
      applyLead: "Send a short email with your CV, a link to your GitHub or Scholar profile if you have one, and a sentence or two about which research direction interests you.",
    },
    collab: {
      eyebrow: "Collaboration",
      title: "Collaboration",
      lead: "We partner with companies and academic groups across food chemistry, fermentation, synthetic biology, nutrition, and microbiology — with extensions into nutraceuticals, cosmetics, and pharmaceuticals.",
      areas: [
        {
          title: "Industry R&D",
          body: "Bilateral and consortium projects with food, ingredient and bioprocessing companies — co-developing AI tools for ingredient discovery, fermentation optimisation, and side-stream valorisation. We engage through Enterprise Ireland Innovation Partnerships, BiOrbic SFI Bioeconomy Research Centre, Horizon Europe MSCA fellowships (Sustain-FIT) and direct industry contracts, with terms managed through UCD's NovaUCD.",
        },
        {
          title: "Joint research proposals",
          body: "Always open to co-developing grant applications with academic partners — UK-Ireland, US-Ireland, EU (Horizon Europe, MSCA), and Irish national schemes (Research Ireland, Enterprise Ireland, EI-SFI co-funded calls). Bringing AI to food, health, microbiology, and bioprocessing. We co-supervise students, share compute and wet-lab pipelines, and partner with groups across Ireland, Europe, North America and Asia.",
        },
        {
          title: "Custom model development",
          body: "We help partners build, fine-tune and deploy domain-specific models tailored to their data and pipelines — from quick feasibility studies to multi-year R&D programmes, with options for dedicated support and on-premise deployment, arranged through UCD's ConsultUCD / NovaUCD.",
        },
        {
          title: "Talks & advisory",
          body: "Invited talks and short-form advisory work on AI strategy for food, ingredients, nutraceuticals, and bioprocessing companies — formal engagements arranged via ConsultUCD, in line with UCD's external activity policy.",
        },
      ],
      ctaTitle: "Have a problem at the AI / food / health interface?",
      ctaLead: "We are happiest in early-stage conversations — long before a contract — to figure out whether what you need is a model, a benchmark, a fermentation experiment, or none of the above.",
      ctaButton: "Start a conversation",
    },
    pillars: [
      { title: "Bioactive Discovery", body: "Leveraging AI to discover and produce bioactive peptides and small molecules from agricultural byproducts." },
      { title: "Smart Biomanufacturing", body: "Leveraging AI for rational experimental design in fermentation and biomanufacturing." },
      { title: "Large language models for AI4Science", body: "Building lightweight pre-trained models for proteins, peptides, and microbial communities — small enough to fine-tune and serve." },
      { title: "AI for Science", body: "Applying LLMs and deep learning across food chemistry, nutritional science, and biochemistry." },
      { title: "Agri-Valorization", body: "Converting agricultural waste into high-value functional ingredients through AI-optimized processes." },
    ],
    projects: [
      "Lightweight pretrained language model for peptide representation. Small enough to fine-tune on a single GPU; strong on bioactivity benchmarks.",
      "Enzyme–substrate pair prediction by fusing ESM-2 protein embeddings with MoLFormer substrate embeddings through specifically designed projection heads and a contrastive learning architecture.",
      "A universal deep-learning architecture for binary classification across many bioactive peptide tasks, with a public webserver and PyTorch / Keras builds.",
      "Protein language-model-based predictor for screening peptides with high antihypertensive (ACE-inhibitory) activity.",
      "Protein language-model-based predictors for allergenic proteins and peptides — a screening tool for food allergy risk.",
      "Computer-aided framework for predicting, screening, and designing antioxidative dipeptides — applied to sorghum proteins.",
      "Comprehensive evaluation and comparison of machine learning methods for QSAR modeling of antioxidant tripeptides.",
    ],
    newsItems: [
      "Welcome Dongyang and Qidong to the AI4FH Lab.",
      "AI4FH Lab is established at UCD. We are open for PhD, MSc, and postdoc inquiries.",
    ],
  },
  zh: {
    nav: {
      home: "首页",
      research: "研究",
      people: "团队",
      publications: "论文",
      news: "动态",
      join: "加入我们",
      collab: "合作",
    },
    chrome: {
      menu: "菜单",
      close: "关闭",
      footerLab: "实验室",
      footerEngage: "联系",
      footerElsewhere: "其他链接",
      openPositions: "开放职位",
      collaborate: "合作交流",
      emailUs: "邮件联系",
      ucdProfile: "UCD 主页",
      footerText: "人工智能赋能食品与健康实验室。<br />生物系统与食品工程学院，<br />爱尔兰都柏林大学。",
    },
    home: {
      heroTitleA: "AI 赋能",
      heroFood: "食品",
      heroTitleB: "与",
      heroHealth: "健康",
      heroLead: "我们面向生物活性化合物发现、智能生物制造和大语言模型开展研究，同时发布开源代码和公共 Web 服务，并与湿实验团队紧密合作。",
      readResearch: "查看研究方向",
      joinLab: "加入实验室 →",
      labIndex: "// 实验室索引 · 实时",
      statModels: "开源模型与服务器",
      statPublished: "已发表预测模型",
      statEstablished: "成立时间",
      research: "研究",
      researchDirections: "研究方向",
      researchLead: "围绕 AI、食品与健康交叉界面的五个活跃方向。",
      seeAllResearch: "查看全部研究 →",
      openSource: "开源",
      modelsTitle: "实验室模型与 Web 服务",
      webserver: "WEB 服务",
      news: "动态",
      allUpdates: "全部动态 →",
      ctaEyebrow: "开放职位",
      ctaTitle: "开放职位",
      ctaLead: "实验室正在招收 MSc / PhD 学生和博士后。欢迎具备机器学习、食品化学、微生物学、计算化学、生物化学、生物信息学或合成生物学背景的申请者。",
      seeOpenPositions: "查看开放职位",
    },
    research: {
      eyebrow: "研究",
      title: "研究",
      lead: "五条研究主线：生物活性发现、智能生物制造、基础模型、更广义的 AI for Science，以及面向产业影响的农业副产物高值化。",
      openSource: "开源",
      modelsTitle: "模型、基准与 Web 服务",
    },
    people: {
      eyebrow: "团队",
      title: "团队",
      lead: "实验室由 Zhenjiao Du 领导，成员背景涵盖食品化学、食品工程、微生物学、药学和机器学习。",
      pi: "课题组负责人",
      groupMembers: "团队成员",
      partner: "终身实验室伙伴",
      partnerRole: "实验室联合创始人（非正式但无可争议）· 首席快乐官与道德指南针",
      joined: "加入时间",
      sinceForever: "一直都在",
      funFact: "有趣事实",
      funFactText: "她加入实验室的时间比实验室成立还早。",
      interests: "兴趣",
      interestsText: "维护工作与生活平衡、烘焙和旅行",
      email: "邮箱",
      alumni: "校友",
    },
    publications: {
      eyebrow: "论文",
      title: "论文",
      lead: "近期代表性论文。完整列表见 Google Scholar。",
      viewScholar: "在 Google Scholar 查看 ↗",
    },
    news: {
      eyebrow: "动态",
      title: "动态",
      lead: "实验室最新消息。",
      featured: "实验室最新动态",
    },
    join: {
      eyebrow: "开放职位",
      title: "开放职位",
      lead: "实验室长期招收不同阶段的成员。欢迎具备机器学习、食品化学、微生物学、计算化学、生物化学、生物信息学或合成生物学背景的申请者。",
      roles: [
        {
          title: "MSc 与 PhD 学生",
          detail: "提供 AI4Science 方向的全额资助机会，研究主题包括生物活性肽、发酵或微生物语言模型。欢迎有编程或湿实验背景的申请者，我们会帮助你补齐跨学科技能。也欢迎申请爱尔兰政府研究生奖学金及其他国内外奖学金。",
        },
        {
          title: "博士后研究人员",
          detail: "欢迎共同申请 MSCA、Wellcome、Research Ireland 等博士后项目。理想申请者能够将 AI 方法与生物化学、微生物学、食品化学或合成生物学等具体领域结合。",
        },
      ],
      howToApply: "如何申请",
      applyLead: "请发送一封简短邮件，附上 CV、GitHub 或 Scholar 主页链接（如有），并用一两句话说明你感兴趣的研究方向。",
    },
    collab: {
      eyebrow: "合作",
      title: "合作",
      lead: "我们与食品化学、发酵、合成生物学、营养和微生物学领域的企业及学术团队合作，并延伸到营养健康产品、化妆品和药物相关应用。",
      areas: [
        {
          title: "产业研发",
          body: "与食品、配料和生物加工企业开展双边或联合项目，共同开发用于配料发现、发酵优化和副产物流高值化的 AI 工具。合作可通过 Enterprise Ireland Innovation Partnerships、BiOrbic SFI Bioeconomy Research Centre、Horizon Europe MSCA fellowship 以及直接产业合同等方式推进，并由 UCD NovaUCD 支持相关条款。",
        },
        {
          title: "联合科研项目",
          body: "欢迎与学术伙伴共同设计科研项目申请，包括 UK-Ireland、US-Ireland、EU Horizon Europe / MSCA，以及 Research Ireland、Enterprise Ireland 等爱尔兰国家项目。我们关注食品、健康、微生物学和生物加工中的 AI 应用，也欢迎学生联合培养、计算资源和湿实验流程共享。",
        },
        {
          title: "定制模型开发",
          body: "我们帮助合作方基于自身数据和流程开发、微调和部署领域专用模型，从快速可行性验证到多年期研发项目均可支持，并可通过 UCD ConsultUCD / NovaUCD 安排合作。",
        },
        {
          title: "报告与咨询",
          body: "可围绕食品、配料、营养健康和生物加工企业的 AI 战略提供邀请报告和短期咨询，相关正式合作将按照 UCD 外部活动政策通过 ConsultUCD 安排。",
        },
      ],
      ctaTitle: "你是否有 AI / 食品 / 健康交叉领域的问题？",
      ctaLead: "我们乐于在项目早期就开始交流，在合同形成之前先判断你需要的是模型、基准、发酵实验，还是完全不同的解决方案。",
      ctaButton: "开始交流",
    },
    pillars: [
      { title: "生物活性发现", body: "利用 AI 从农业副产物中发现并生产生物活性肽和小分子。" },
      { title: "智能生物制造", body: "利用 AI 进行发酵和生物制造中的理性实验设计。" },
      { title: "AI4Science 大语言模型", body: "构建面向蛋白质、肽和微生物群落的轻量预训练模型，便于微调和部署。" },
      { title: "AI for Science", body: "将 LLM 和深度学习应用于食品化学、营养科学和生物化学。" },
      { title: "农业副产物高值化", body: "通过 AI 优化流程，将农业废弃物转化为高价值功能性配料。" },
    ],
    projects: [
      "轻量级肽表示预训练语言模型，可在单 GPU 上微调，并在生物活性预测基准中表现稳健。",
      "融合 ESM-2 蛋白嵌入与 MoLFormer 底物嵌入，通过专门设计的投影头和对比学习架构预测酶-底物配对。",
      "面向多种生物活性肽二分类任务的通用深度学习架构，提供公共 Web 服务以及 PyTorch / Keras 实现。",
      "基于蛋白质语言模型的预测器，用于筛选高抗高血压活性的 ACE 抑制肽。",
      "基于蛋白质语言模型的过敏原蛋白和肽预测工具，用于食品过敏风险筛查。",
      "用于预测、筛选和设计抗氧化二肽的计算辅助框架，并应用于高粱蛋白。",
      "对抗氧化三肽 QSAR 建模中的多种机器学习方法进行系统评估和比较。",
    ],
    newsItems: [
      "欢迎 Dongyang 和 Qidong 加入 AI4FH 实验室。",
      "AI4FH 实验室在 UCD 成立。我们开放 PhD、MSc 和博士后咨询。",
    ],
  },
};
